# per default we only run over the files in the python package
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
        # but no large files anywhere ;)
        files: ''
        exclude: ""
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      # Run the linter.
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        files: '^votingsystemsim/'
        exclude: ''
-   repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        files: '^votingsystemsim/'
        exclude: ''