# per default we only run over the files in the python package
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
        # but no large files anywhere ;)
        files: ''
        exclude: ""
-   repo: local
    hooks:
      - id: ruff_check
        name: ruff_check
        entry: poetry run ruff check
        language: system
        types: [ python, pyi, jupyter ]
        args: [ --fix ]
        files: '^votingsystemsim/'
-   repo: local
    hooks:
      - id: ruff_format
        name: ruff_format 
        entry: poetry run ruff format
        language: system
        types: [ python, pyi, jupyter ]
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        files: '^votingsystemsim/'
        exclude: ''
-   repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        files: '^votingsystemsim/'
        exclude: ''