# name: Ruff
# on: [ push, pull_request ]
# jobs:
#   ruff:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: astral-sh/ruff-action@v1

name: Run pre-commit checks
  on: [ push, pull_request ]
  run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files